import type { Metadata } from "next";
import "./globals.css";

import {ClerkProvider} from '@clerk/nextjs'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Providers from "./Provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <ClerkProvider>
     
    <html lang="en">
      <body
      >
        <Providers>
          
         
        {children}
        </Providers> 
      </body>
    </html>
   
    </ClerkProvider>
   
  );
}
