import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider } from '@clerk/nextjs'
import Providers from "./Provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>

      <html lang="en">
        <body
        >
          <Providers>


            {children}
            <Toaster />
          </Providers>
        </body>
      </html>

    </ClerkProvider>

  );
}
